name = "cloudflare-worker-automation"
compatibility_date = "2022-06-08"
main = "index.js"

kv_namespaces = [
  { binding = "VERSION_KV", preview_id = "3f5c1d02faf84582ac50dc91254f3144", id = "2c5b42658d8240229be0922a9c7354ee" }
]